defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

domain: ibrahimWassouf.github.io
url: https://ibrahimWassouf.github.io
baseurl: /studyGale/
